app:
   server: localhost
   port: '8080'
   deploy: norbekov.herokuapp.com
  

db:
   dbname: ybvyqagf
   host: 	dumbo.db.elephantsql.com 
   port: '5432'
   sslmode: disable
   username: ybvyqagf



